services:
  backend_rh:
    build:
      context: ./
      dockerfile: infra/docker/backend.Dockerfile
    container_name: backend-rh-pulze
    volumes:
      - ./backend:/app/backend
      - ./infra/airflow:/app/infra/airflow
      - ./infra/mlflow:/app/infra/mlflow
      - ./.github:/app/.github
      - ./data:/app/data

    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
      - CHROMA_PATH=/app/vector_db/chroma_storage/embedding_db
    restart: on-failure

  db_rh:
    image: postgres:15-alpine
    container_name: rh_pulze_db
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend_rh:
    build: ../frontend-rh-pulze
    image: "frontend_rh_pulze"
    ports: 
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_API=http://backend:8000
    volumes:
      - ../frontend-rh-pulze/src:/app/src  
      - ../frontend-rh-pulze/public:/app/public 
      - ../frontend-rh-pulze/package.json:/app/package.json  
      - ../frontend-rh-pulze/package-lock.json:/app/package-lock.json
    depends_on:
      - backend_rh

  chromadb_rh:
    image: chromadb/chroma
    container_name: chromadb
    ports:
      - "8005:8000"
    volumes:
      - chroma_data:/data
    restart: always

  mlflow_rh:
    build:
      context: ../..
      dockerfile: infra/docker/mlflow.Dockerfile
    container_name: mlflow_server
    ports:
      - "5000:5000"
    volumes:
      - ../../mlruns:/mlflow/artifacts
      - ../../mlflow.db:/mlflow/mlflow.db
    restart: always
volumes:
  chroma_rh:
  db_rh:
  
  
  