name: Run Unit Tests

on:
  push:
    branches: [ develop, main ]

jobs:
  test: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Cache UV dependencies
        uses: actions/cache@v3
        with:
          path: .cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('pyproject.toml') }}
          
      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Exécuter les tests
        run: uv run pytest -v
        env:
        PYTHONPATH: ${{ github.workspace }}