name: Run Unit Tests

on:
  push:
    branches: [ develop, main ]

jobs:
  lint:  
    runs-on: ubuntu-latest 

    steps:  
      - name: Checkout code  
        uses: actions/checkout@v4 

      - name: Setup Python  
        uses: actions/setup-python@v5 
        with:
          python-version: '3.10' 

      - name: Install dependencies  
        run: |
          python -m pip install --upgrade pip  # Met à jour pip
          pip install -r requirements.txt  # Installe les librairies du projet
          pip install flake8  # Installe l’outil de linting

      - name: Run Lint  # Lancer l’analyse du code
        run: flake8 . --ignore=F401,E501,W291,W292,E302,E225,E226,E111,E117,E265,W293,W391,E203,E231,E121,E126,F811,E201

  test: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install PyTorch (CPU)
        run: pip install torch --index-url https://download.pytorch.org/whl/cpu

      - name: Install sentence-transformers
        run: pip install sentence-transformers

      - name: Install the project dependencies
        run: uv sync --locked --all-extras --dev

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Exécuter les tests
        run: uv run pytest -v
